### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by gbacskai** [gbacskai/geotracker#2]
When I click on the Device History in one of the row it should open a google map with the location pinned.

**Comment by gbacskai** [comment]
<img width="956" alt="Screen Shot 2021-03-18 at 11 14 20 pm" src="https://user-images.githubusercontent.com/16809418/111624448-d0a93780-883f-11eb-9495-7395f7a25eb2.png">

when I click on location should open the location in a new page in google maps (will set a new key, please use a temporary one for now)

**Comment by sanjayradadiya** [comment]
Please test this - https://github.com/gbacskai/geotracker/pull/5
